# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

TEMPLATE = app
TARGET = qtclient
QT += core gui network

HEADERS += ./QtClient.h \
           ./TcpClient.h
SOURCES += ./QtClient.cpp \
           ./main.cpp \
           ./TcpClient.cpp
FORMS += ./QtClient.ui
